classes:
  - card
  - black_joker
  - joker
  - ace_of_spades
  - 2_of_spades
  - 3_of_spades
  - 4_of_spades
  - 5_of_spades
  - 6_of_spades
  - 7_of_spades
  - 8_of_spades
  - 9_of_spades
  - 10_of_spades
  - jack_of_spades
  - queen_of_spades
  - king_of_spades
  - ace_of_diamons
  - 2_of_diamons
  - 3_of_diamons
  - 4_of_diamons
  - 5_of_diamons
  - 6_of_diamons
  - 7_of_diamons
  - 8_of_diamons
  - 9_of_diamons
  - 10_of_diamons
  - jack_of_diamons
  - queen_of_diamons
  - king_of_diamons
  - ace_of_hearts
  - 2_of_hearts
  - 3_of_hearts
  - 4_of_hearts
  - 5_of_hearts
  - 6_of_hearts
  - 7_of_hearts
  - 8_of_hearts
  - 9_of_hearts
  - 10_of_hearts
  - jack_of_hearts
  - queen_of_hearts
  - king_of_hearts
  - ace_of_clubs
  - 2_of_clubs
  - 3_of_clubs
  - 4_of_clubs
  - 5_of_clubs
  - 7_of_clubs
  - 6_of_clubs
  - 8_of_clubs
  - 9_of_clubs
  - 10_of_clubs
  - jack_of_clubs
  - queen_of_clubs
  - king_of_clubs