labels:
  - As
  - 2s
  - 3s
  - 4s
  - 5s
  - 6s
  - 7s
  - 8s
  - 9s
  - 10s
  - Js
  - Qs
  - Ks
  - Ad
  - 2d
  - 3d
  - 4d
  - 5d
  - 6d
  - 7d
  - 8d
  - 9d
  - 10d
  - Jd
  - Qd
  - kd
  - Ah
  - 2h
  - 3h
  - 4h
  - 5h
  - 6h
  - 7h
  - 8h
  - 9h
  - 10h
  - Jh
  - Qh
  - Kh
  - Ac
  - 2c
  - 3c
  - 4c
  - 5c
  - 7c
  - 6c
  - 8c
  - 9c
  - 10c
  - Jc
  - Qc
  - Kc

logger:
  name: object-detector
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"