name: tensorflow-object-detector
channels:
- https://conda.anaconda.org/menpo
- defaults
- conda-forge
- anaconda
- conda-forge/label/cf201901
dependencies:
    - python=3.7
    - Cython
    - contextlib2
    - pillow
    - lxml
    - matplotlib
    - numpy
    - protobuf
    - pycocotools
    - cudatoolkit=10.0
    - cudnn=7.6
    - cupti=10.0
    - scipy
    - tensorflow-gpu==1.15
    - pytest
    - pyyaml
    - pandas
    - seaborn
    - pip
    - pip:
        - opencv-contrib-python==4.1.2.30
        - untangle
        - tensorboard