item {
	id: 1
	name: card
}
item {
	id: 2
	name: black_joker
}
item {
	id: 3
	name: joker
}
item {
	id: 4
	name: ace_of_spades
}
item {
	id: 5
	name: 2_of_spades
}
item {
	id: 6
	name: 3_of_spades
}
item {
	id: 7
	name: 4_of_spades
}
item {
	id: 8
	name: 5_of_spades
}
item {
	id: 9
	name: 6_of_spades
}
item {
	id: 10
	name: 7_of_spades
}
item {
	id: 11
	name: 8_of_spades
}
item {
	id: 12
	name: 9_of_spades
}
item {
	id: 13
	name: 10_of_spades
}
item {
	id: 14
	name: jack_of_spades
}
item {
	id: 15
	name: queen_of_spades
}
item {
	id: 16
	name: king_of_spades
}
item {
	id: 17
	name: ace_of_diamons
}
item {
	id: 18
	name: 2_of_diamons
}
item {
	id: 19
	name: 3_of_diamons
}
item {
	id: 20
	name: 4_of_diamons
}
item {
	id: 21
	name: 5_of_diamons
}
item {
	id: 22
	name: 6_of_diamons
}
item {
	id: 23
	name: 7_of_diamons
}
item {
	id: 24
	name: 8_of_diamons
}
item {
	id: 25
	name: 9_of_diamons
}
item {
	id: 26
	name: 10_of_diamons
}
item {
	id: 27
	name: jack_of_diamons
}
item {
	id: 28
	name: queen_of_diamons
}
item {
	id: 29
	name: king_of_diamons
}
item {
	id: 30
	name: ace_of_hearts
}
item {
	id: 31
	name: 2_of_hearts
}
item {
	id: 32
	name: 3_of_hearts
}
item {
	id: 33
	name: 4_of_hearts
}
item {
	id: 34
	name: 5_of_hearts
}
item {
	id: 35
	name: 6_of_hearts
}
item {
	id: 36
	name: 7_of_hearts
}
item {
	id: 37
	name: 8_of_hearts
}
item {
	id: 38
	name: 9_of_hearts
}
item {
	id: 39
	name: 10_of_hearts
}
item {
	id: 40
	name: jack_of_hearts
}
item {
	id: 41
	name: queen_of_hearts
}
item {
	id: 42
	name: king_of_hearts
}
item {
	id: 43
	name: ace_of_clubs
}
item {
	id: 44
	name: 2_of_clubs
}
item {
	id: 45
	name: 3_of_clubs
}
item {
	id: 46
	name: 4_of_clubs
}
item {
	id: 47
	name: 5_of_clubs
}
item {
	id: 48
	name: 7_of_clubs
}
item {
	id: 49
	name: 6_of_clubs
}
item {
	id: 50
	name: 8_of_clubs
}
item {
	id: 51
	name: 9_of_clubs
}
item {
	id: 52
	name: 10_of_clubs
}
item {
	id: 53
	name: jack_of_clubs
}
item {
	id: 54
	name: queen_of_clubs
}
item {
	id: 55
	name: king_of_clubs
}
